name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set RELEASE_NAME
      run: echo "RELEASE_NAME=$(if [ -n \"$GITHUB_REF_NAME\" ]; then echo \"$GITHUB_REF_NAME\"; else echo \"latest\"; fi)" >> $GITHUB_ENV

    - name: Debug
      run: echo "RELEASE_NAME=${{ env.RELEASE_NAME }}"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t rcastro95/app-rcastro-nginx:latest .
        docker tag rcastro95/app-rcastro-nginx:latest your-docker-username/app-rcastro-nginx:${{ env.RELEASE_NAME }}
        docker images

    - name: Push Docker Image
      run: |
        docker push rcastro95/app-rcastro-nginx:latest
        docker push rcastro95/app-rcastro-nginx:${{ env.RELEASE_NAME }}
